### ISSUE TITLE
Support for Minecraft Java / Forge/Fabric

### ISSUE THREAD

**Issue by Micaxs** [tebexio/Tebex-RconAdapter#3]
Your RCON Adapter which seems to be now forced on tebex website does not support minecraft rcon conenctions and there is no way to change back to the legacy way, this prevents people from using tebex to process commands on a Minecraft Forge 1.19.2/1.20.1 server as the "suggested plugin/mod" does not work and we use RCON to integrate it successfully. But with this new adaptor this seems to be not possible anymore.

**Comment by WildBamaBoy** [comment]
Hi, Minecraft support is planned soon. For right now, the previous direct RCON integration has been re-enabled for affected webstores.
